import { BookOpen, Globe2, LayoutDashboard, Puzzle } from '@lucide/astro';

export const projects = [
  {
    id: '01',
    title: 'Watermark Remover',
    description:
      'A local tool for removing watermarks from images generated by nano banana. Built with Vue.js for high performance.',
    tech: ['Vue.js', 'Canvas API'],
    Icon: Globe2,
    link: 'https://wmremover.aouos.com/',
  },
  {
    id: '02',
    title: 'React 19 Learning',
    description:
      'A project-driven learning system for React 19, covering 30 lessons from core fundamentals to source-code mastery across 4 progressive phases.',
    tech: ['React 19', 'VitePress'],
    Icon: BookOpen,
    link: 'https://react.aouos.com',
  },
  {
    id: '03',
    title: 'AOUI',
    description:
      'A design token reference for the AOUI system, documenting colors, spacing, radii, typography, and motion for consistent product interfaces.',
    tech: ['Design Tokens', 'UI System'],
    Icon: LayoutDashboard,
    link: 'https://aoui.aouos.com/',
  },
  {
    id: '04',
    title: 'AOUOS Logo',
    description:
      'A dedicated brand asset page for downloading the AOUOS logo in SVG plus transparent and white-background PNG exports in multiple sizes.',
    tech: ['SVG', 'Brand Assets'],
    Icon: Puzzle,
    link: 'https://logo.aouos.com/',
  },
] as const;
